Description: Faces recognition
Engine: gotpl
Home: https://kibernetika.ai/
Keywords:
- kibernetika
- openvino
- face detection
- face recognition
Maintainers:
- Email: support@kuberlab.com
  Name: kuberlab
Name: ponchik
Type: mlapp-v2
Version: 1.0.0
