storage:
  value: default
  wizard:
    name: "Storage Configuration"
    kind: cluster_storage

src:
  value: https://github.com/kibernetika-ai/ponchik
  accountId: ''
  revision: ''
  wizard:
    name: "Source Code"
    kind: git

model:
  value: 'facenet-pretrained'
  version: '1.0.0-openvino-cpu'
  workspace: 'kuberlab-demo'
  wizard:
    name: "Pretrained catalog model"
    kind: model

faces:
  value: 'svod-faces'
  version: '1.1.7'
  workspace: 'svod'
  wizard:
    name: "Faces Dataset"
    kind: dataset

bgrm:
  value: 'coco-bg-rm'
  version: '1.0.0'
  workspace: 'kuberlab-demo'
  wizard:
    name: "Background removal model"
    kind: model

detection_bgrm_align:
  value: true
  wizard:
    name: Use background removal before face detection on alignment
    kind: boolean

detection_bgrm_serving:
  value: false
  wizard:
    name: Use background removal before face detection on recognition (serving)
    kind: boolean

detection_debug:
  value: false
  wizard:
    name: Return debug info on detection and recognition
    kind: boolean

process_clarified:
  value: true
  wizard:
    name: Process clarified faces with serving, use sent images as is, without preliminary face detection
    kind: boolean

process_uploaded:
  value: true
  wizard:
    name: Process sent images with preliminary face detection
    kind: boolean
