kind: MLApp
metadata:
  name: ponchik
spec:
  default_mount_path: /notebooks
  default_read_only: false
  package_manager: pip3
  packages:
  - manager: pip3
  tasks:
  - name: prepare-dataset
    resources:
    - command: python prepare.py
        --input_dir $FACES_DIR
        --aligned_dir $TRAINING_DIR/aligned
        {{- if and .bgrm.value .detection_bgrm_align.value }}
        --bg_remove_path $BGRM_DIR
        {{- end }}
        --model_path $FACENET_DIR/facenet.xml
        --classifiers_dir $TRAINING_DIR/classifiers
        --model_name {{ .app_name }}
        --model_version 1.0.0-$(date +%s)
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino-gpu
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 512Mi
      restartPolicy: Never
      volumes:
      - name: src
      - name: faces
      - name: training
      - name: facenet
      {{- if and .bgrm.value .detection_bgrm_align.value }}
      - name: bgrm
      {{- end }}
      workDir: $SRC_DIR
  {{- if .process_clarified.value }}
  - name: prepare-clarified
    resources:
    - command: python prepare.py
        --input_dir $CLARIFIED_DIR
        --clarified
        --aligned_dir $TRAINING_DIR/aligned
        --model_path $FACENET_DIR/facenet.xml
        --classifiers_dir $TRAINING_DIR/classifiers
        --model_name {{ .app_name }}
        --model_version 1.0.0-$(date +%s)
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino-gpu
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 512Mi
      restartPolicy: Never
      volumes:
      - name: src
      - name: clarified
      - name: training
      - name: facenet
      workDir: $SRC_DIR
  {{- end }}
  {{- if .process_uploaded.value }}
  - name: prepare-uploaded
    resources:
    - command: python prepare.py
        --input_dir $UPLOADED_DIR
        --aligned_dir $TRAINING_DIR/aligned
        {{- if and .bgrm.value .detection_bgrm_align.value }}
        --bg_remove_path $BGRM_DIR
        {{- end }}
        --model_path $FACENET_DIR/facenet.xml
        --classifiers_dir $TRAINING_DIR/classifiers
        --complementary
        --model_name {{ .app_name }}
        --model_version 1.0.0-$(date +%s)
      images:
        cpu: kuberlab/serving:latest-openvino
        gpu: kuberlab/serving:latest-openvino-gpu
      name: worker
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: 8Gi
        requests:
          cpu: "1"
          memory: 512Mi
      restartPolicy: Never
      volumes:
      - name: src
      - name: uploaded
      - name: training
      - name: facenet
      {{- if and .bgrm.value .detection_bgrm_align.value }}
      - name: bgrm
      {{- end }}
      workDir: $SRC_DIR
  {{- end }}
  uix:
  - default_volume_mapping: true
    displayName: Jupyter
    images:
      cpu: kuberlab/tensorflow:cpu-36-1.9.0-full
    name: jupyter
    ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 512Mi
  serving:
  - name: serving
    displayName: Faces detection serving
    images:
      cpu: "kuberlab/serving:latest-openvino"
      gpu: "kuberlab/serving:latest-openvino-gpu"
    command: >-
      pip install slackclient croniter &&
      kserving --driver openvino --model-path $FACENET_DIR/facenet.xml
      --hooks serving_hook.py
      {{- if and .bgrm.value .detection_bgrm_serving.value }}
      -o bg_remove_path=$BGRM_DIR
      {{- end }}
      -o classifiers_dir=$MODEL_DIR
      -o flexible_batch_size=True
      {{- if .detection_debug.value }}
      -o debug=true
      {{- end }}
      {{- if .process_clarified.value }}
      -o clarified_dir=$CLARIFIED_DIR
      {{- end }}
      {{- if .process_uploaded.value }}
      -o uploaded_dir=$UPLOADED_DIR
      {{- end }}
      -o threshold=0.25,0.3,0.3
      -o project_name={{ .app_name }}
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 200m
        memory: 256M
      limits:
        cpu: 4000m
        memory: 4Gi
    spec:
      params:
      - name: input
        type: bytes
      response:
      - name: output
        type: bytes
        shape:
        - 1
        - -1
      - name: table_output
        type: string
        shape:
        - -1
      rawInput: true
      model: any
      template: "image"
      outFilter:
        - output
      outMimeType: "image/jpeg"
    workDir: $SRC_DIR
    sources:
    - gitRepo:
        repository: {{ gitRepo .src.value }}
        accountId: '{{ .src.accountId }}'
        revision: '{{ .src.revision }}'
      name: src
      subPath: {{ gitSubPath .src.value }}
    - name: facenet
      model:
        workspace: {{ .model.workspace }}
        model: {{ .model.value }}
        version: {{ .model.version }}
    - name: face-detection
      model:
        workspace: kuberlab-demo
        model: openvino-face-detection
        version: 1.4.0-cpu
    {{- if and .bgrm.value .detection_bgrm_serving.value }}
    - name: bgrm
      model:
        workspace: {{ .bgrm.workspace }}
        model: {{ .bgrm.value }}
        version: {{ .bgrm.version }}
    {{- end }}
    {{- if .process_clarified.value }}
    - name: clarified
      clusterStorage: {{ .storage.value }}
      subPath: /shared/{{ .app_name }}-clarified
    {{- end }}
    {{- if .process_uploaded.value }}
    - name: uploaded
      clusterStorage: {{ .storage.value }}
      subPath: /shared/{{ .app_name }}-uploaded
    {{- end }}
    ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  volumes:
  - name: training
    clusterStorage: '{{ .storage.value }}'
  - name: src
    gitRepo:
      repository: {{ gitRepo .src.value }}
      accountId: '{{ .src.accountId }}'
      revision: '{{ .src.revision }}'
    subPath: {{ gitSubPath .src.value }}
  - name: lib
    clusterStorage: '{{ .storage.value }}'
    isLibDir: true
  - name: code
    clusterStorage: '{{ .storage.value }}'
    mountPath: /notebooks
    subPath: code
  - name: facenet
    model:
      workspace: {{ .model.workspace }}
      model: {{ .model.value }}
      version: {{ .model.version }}
  - name: faces
  {{- if .faces.value }}
    datasetFS:
      workspace: {{ .faces.workspace }}
      dataset: {{ .faces.value }}
      version: {{ .faces.version }}
  {{- else }}
    clusterStorage: {{ .storage.value }}
  {{- end }}
  {{- if .bgrm.value }}
  - name: bgrm
    model:
      workspace: {{ .bgrm.workspace }}
      model: {{ .bgrm.value }}
      version: {{ .bgrm.version }}
  {{- end }}
  {{- if .process_clarified.value }}
  - name: clarified
    clusterStorage: {{ .storage.value }}
    subPath: /shared/{{ .app_name }}-clarified
  {{- end }}
  {{- if .process_uploaded.value }}
  - name: uploaded
    clusterStorage: {{ .storage.value }}
    subPath: /shared/{{ .app_name }}-uploaded
  {{- end }}
